mutation updateColumnsOrder($updates: [columns_updates!]!){
    update_columns_many(updates: $updates){
        returning{
            id
            board_id
            name
            position
            cards{
                id
                column_id
                title
                description
                position
                assignee
            }
        }
    }
}

mutation insertOneColumn($object: columns_insert_input!){
    insert_columns_one(object: $object){
            id
            board_id
            name
            position
    }
}

mutation deleteColumnByID($id: uuid!){
    delete_columns_by_pk(id: $id){
            id
            board_id
            name
            position
    }
}

mutation updateOneColumn($id: uuid!, $update: columns_set_input!){
    update_columns_by_pk(pk_columns: {id: $id}, _set: $update){
            id
            board_id
            name
            position
    }
}
