/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "mutation addBoard($object: boards_insert_input!) {\n  insert_boards_one(object: $object) {\n    id\n    name\n    owner\n    position\n  }\n}\n\nmutation deleteBoard($boardId: uuid!) {\n  delete_boards_by_pk(id: $boardId) {\n    id\n  }\n}\n\nmutation editBoard($set: boards_set_input, $id: uuid!) {\n  update_boards_by_pk(pk_columns: {id: $id}, _set: $set) {\n    id\n    name\n    owner\n    position\n  }\n}": typeof types.AddBoardDocument,
    "mutation updateCardOrder($updates: [cards_updates!]!) {\n  update_cards_many(updates: $updates) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation updateColumnCardOrder($where: cards_bool_exp!, $set: cards_set_input) {\n  update_cards(where: $where, _set: $set) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation addCard($object: cards_insert_input!) {\n  insert_cards_one(object: $object) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation removeCard($id: uuid!) {\n  delete_cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation editCard($id: uuid!, $set: cards_set_input) {\n  update_cards_by_pk(_set: $set, pk_columns: {id: $id}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}": typeof types.UpdateCardOrderDocument,
    "mutation updateColumnsOrder($updates: [columns_updates!]!) {\n  update_columns_many(updates: $updates) {\n    returning {\n      id\n      board_id\n      name\n      position\n      cards {\n        id\n        column_id\n        title\n        description\n        position\n        assignee\n      }\n    }\n  }\n}\n\nmutation insertOneColumn($object: columns_insert_input!) {\n  insert_columns_one(object: $object) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation deleteColumnByID($id: uuid!) {\n  delete_columns_by_pk(id: $id) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation updateOneColumn($id: uuid!, $update: columns_set_input!) {\n  update_columns_by_pk(pk_columns: {id: $id}, _set: $update) {\n    id\n    board_id\n    name\n    position\n  }\n}": typeof types.UpdateColumnsOrderDocument,
    "query getAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nquery getBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}": typeof types.GetAllBoardsDocument,
    "query getCard($id: uuid!) {\n  cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromColumnId($id: uuid!) {\n  cards(where: {column_id: {_eq: $id}}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromBoardId($id: uuid!) {\n  cards(where: {column: {board_id: {_eq: $id}}}) {\n    id\n    title\n    description\n    position\n    assignee\n    column_id\n  }\n}": typeof types.GetCardDocument,
    "query getAllColumnsAllCards {\n  columns {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}) {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getColumn($id: uuid!) {\n  columns_by_pk(id: $id) {\n    board_id\n    id\n    name\n    position\n  }\n}": typeof types.GetAllColumnsAllCardsDocument,
    "query GetAllMutations {\n  __type(name: \"mutation_root\") {\n    name\n    fields {\n      name\n      description\n      args {\n        name\n        type {\n          name\n          kind\n        }\n      }\n    }\n  }\n}": typeof types.GetAllMutationsDocument,
    "subscription subscribeAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nsubscription subscribeBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}": typeof types.SubscribeAllBoardsDocument,
    "subscription subscribeAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}, order_by: {position: asc}) {\n    board_id\n    id\n    name\n    position\n    cards(order_by: {position: asc}) {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}": typeof types.SubscribeAllColumnsCardsFromBoardIdDocument,
};
const documents: Documents = {
    "mutation addBoard($object: boards_insert_input!) {\n  insert_boards_one(object: $object) {\n    id\n    name\n    owner\n    position\n  }\n}\n\nmutation deleteBoard($boardId: uuid!) {\n  delete_boards_by_pk(id: $boardId) {\n    id\n  }\n}\n\nmutation editBoard($set: boards_set_input, $id: uuid!) {\n  update_boards_by_pk(pk_columns: {id: $id}, _set: $set) {\n    id\n    name\n    owner\n    position\n  }\n}": types.AddBoardDocument,
    "mutation updateCardOrder($updates: [cards_updates!]!) {\n  update_cards_many(updates: $updates) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation updateColumnCardOrder($where: cards_bool_exp!, $set: cards_set_input) {\n  update_cards(where: $where, _set: $set) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation addCard($object: cards_insert_input!) {\n  insert_cards_one(object: $object) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation removeCard($id: uuid!) {\n  delete_cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation editCard($id: uuid!, $set: cards_set_input) {\n  update_cards_by_pk(_set: $set, pk_columns: {id: $id}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}": types.UpdateCardOrderDocument,
    "mutation updateColumnsOrder($updates: [columns_updates!]!) {\n  update_columns_many(updates: $updates) {\n    returning {\n      id\n      board_id\n      name\n      position\n      cards {\n        id\n        column_id\n        title\n        description\n        position\n        assignee\n      }\n    }\n  }\n}\n\nmutation insertOneColumn($object: columns_insert_input!) {\n  insert_columns_one(object: $object) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation deleteColumnByID($id: uuid!) {\n  delete_columns_by_pk(id: $id) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation updateOneColumn($id: uuid!, $update: columns_set_input!) {\n  update_columns_by_pk(pk_columns: {id: $id}, _set: $update) {\n    id\n    board_id\n    name\n    position\n  }\n}": types.UpdateColumnsOrderDocument,
    "query getAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nquery getBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}": types.GetAllBoardsDocument,
    "query getCard($id: uuid!) {\n  cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromColumnId($id: uuid!) {\n  cards(where: {column_id: {_eq: $id}}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromBoardId($id: uuid!) {\n  cards(where: {column: {board_id: {_eq: $id}}}) {\n    id\n    title\n    description\n    position\n    assignee\n    column_id\n  }\n}": types.GetCardDocument,
    "query getAllColumnsAllCards {\n  columns {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}) {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getColumn($id: uuid!) {\n  columns_by_pk(id: $id) {\n    board_id\n    id\n    name\n    position\n  }\n}": types.GetAllColumnsAllCardsDocument,
    "query GetAllMutations {\n  __type(name: \"mutation_root\") {\n    name\n    fields {\n      name\n      description\n      args {\n        name\n        type {\n          name\n          kind\n        }\n      }\n    }\n  }\n}": types.GetAllMutationsDocument,
    "subscription subscribeAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nsubscription subscribeBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}": types.SubscribeAllBoardsDocument,
    "subscription subscribeAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}, order_by: {position: asc}) {\n    board_id\n    id\n    name\n    position\n    cards(order_by: {position: asc}) {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}": types.SubscribeAllColumnsCardsFromBoardIdDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation addBoard($object: boards_insert_input!) {\n  insert_boards_one(object: $object) {\n    id\n    name\n    owner\n    position\n  }\n}\n\nmutation deleteBoard($boardId: uuid!) {\n  delete_boards_by_pk(id: $boardId) {\n    id\n  }\n}\n\nmutation editBoard($set: boards_set_input, $id: uuid!) {\n  update_boards_by_pk(pk_columns: {id: $id}, _set: $set) {\n    id\n    name\n    owner\n    position\n  }\n}"): (typeof documents)["mutation addBoard($object: boards_insert_input!) {\n  insert_boards_one(object: $object) {\n    id\n    name\n    owner\n    position\n  }\n}\n\nmutation deleteBoard($boardId: uuid!) {\n  delete_boards_by_pk(id: $boardId) {\n    id\n  }\n}\n\nmutation editBoard($set: boards_set_input, $id: uuid!) {\n  update_boards_by_pk(pk_columns: {id: $id}, _set: $set) {\n    id\n    name\n    owner\n    position\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation updateCardOrder($updates: [cards_updates!]!) {\n  update_cards_many(updates: $updates) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation updateColumnCardOrder($where: cards_bool_exp!, $set: cards_set_input) {\n  update_cards(where: $where, _set: $set) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation addCard($object: cards_insert_input!) {\n  insert_cards_one(object: $object) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation removeCard($id: uuid!) {\n  delete_cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation editCard($id: uuid!, $set: cards_set_input) {\n  update_cards_by_pk(_set: $set, pk_columns: {id: $id}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}"): (typeof documents)["mutation updateCardOrder($updates: [cards_updates!]!) {\n  update_cards_many(updates: $updates) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation updateColumnCardOrder($where: cards_bool_exp!, $set: cards_set_input) {\n  update_cards(where: $where, _set: $set) {\n    returning {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nmutation addCard($object: cards_insert_input!) {\n  insert_cards_one(object: $object) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation removeCard($id: uuid!) {\n  delete_cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nmutation editCard($id: uuid!, $set: cards_set_input) {\n  update_cards_by_pk(_set: $set, pk_columns: {id: $id}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "mutation updateColumnsOrder($updates: [columns_updates!]!) {\n  update_columns_many(updates: $updates) {\n    returning {\n      id\n      board_id\n      name\n      position\n      cards {\n        id\n        column_id\n        title\n        description\n        position\n        assignee\n      }\n    }\n  }\n}\n\nmutation insertOneColumn($object: columns_insert_input!) {\n  insert_columns_one(object: $object) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation deleteColumnByID($id: uuid!) {\n  delete_columns_by_pk(id: $id) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation updateOneColumn($id: uuid!, $update: columns_set_input!) {\n  update_columns_by_pk(pk_columns: {id: $id}, _set: $update) {\n    id\n    board_id\n    name\n    position\n  }\n}"): (typeof documents)["mutation updateColumnsOrder($updates: [columns_updates!]!) {\n  update_columns_many(updates: $updates) {\n    returning {\n      id\n      board_id\n      name\n      position\n      cards {\n        id\n        column_id\n        title\n        description\n        position\n        assignee\n      }\n    }\n  }\n}\n\nmutation insertOneColumn($object: columns_insert_input!) {\n  insert_columns_one(object: $object) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation deleteColumnByID($id: uuid!) {\n  delete_columns_by_pk(id: $id) {\n    id\n    board_id\n    name\n    position\n  }\n}\n\nmutation updateOneColumn($id: uuid!, $update: columns_set_input!) {\n  update_columns_by_pk(pk_columns: {id: $id}, _set: $update) {\n    id\n    board_id\n    name\n    position\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query getAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nquery getBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}"): (typeof documents)["query getAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nquery getBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query getCard($id: uuid!) {\n  cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromColumnId($id: uuid!) {\n  cards(where: {column_id: {_eq: $id}}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromBoardId($id: uuid!) {\n  cards(where: {column: {board_id: {_eq: $id}}}) {\n    id\n    title\n    description\n    position\n    assignee\n    column_id\n  }\n}"): (typeof documents)["query getCard($id: uuid!) {\n  cards_by_pk(id: $id) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromColumnId($id: uuid!) {\n  cards(where: {column_id: {_eq: $id}}) {\n    id\n    column_id\n    title\n    description\n    position\n    assignee\n  }\n}\n\nquery getCardsFromBoardId($id: uuid!) {\n  cards(where: {column: {board_id: {_eq: $id}}}) {\n    id\n    title\n    description\n    position\n    assignee\n    column_id\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query getAllColumnsAllCards {\n  columns {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}) {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getColumn($id: uuid!) {\n  columns_by_pk(id: $id) {\n    board_id\n    id\n    name\n    position\n  }\n}"): (typeof documents)["query getAllColumnsAllCards {\n  columns {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}) {\n    board_id\n    id\n    name\n    position\n    cards {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}\n\nquery getColumn($id: uuid!) {\n  columns_by_pk(id: $id) {\n    board_id\n    id\n    name\n    position\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "query GetAllMutations {\n  __type(name: \"mutation_root\") {\n    name\n    fields {\n      name\n      description\n      args {\n        name\n        type {\n          name\n          kind\n        }\n      }\n    }\n  }\n}"): (typeof documents)["query GetAllMutations {\n  __type(name: \"mutation_root\") {\n    name\n    fields {\n      name\n      description\n      args {\n        name\n        type {\n          name\n          kind\n        }\n      }\n    }\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "subscription subscribeAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nsubscription subscribeBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}"): (typeof documents)["subscription subscribeAllBoards {\n  boards {\n    id\n    name\n    position\n    owner\n  }\n}\n\nsubscription subscribeBoard($id: uuid!) {\n  boards_by_pk(id: $id) {\n    id\n    name\n    position\n    owner\n  }\n}"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "subscription subscribeAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}, order_by: {position: asc}) {\n    board_id\n    id\n    name\n    position\n    cards(order_by: {position: asc}) {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}"): (typeof documents)["subscription subscribeAllColumnsCardsFromBoardId($id: uuid!) {\n  columns(where: {board_id: {_eq: $id}}, order_by: {position: asc}) {\n    board_id\n    id\n    name\n    position\n    cards(order_by: {position: asc}) {\n      id\n      column_id\n      title\n      description\n      position\n      assignee\n    }\n  }\n}"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;